[package]
name = "first_request"
version = "0.1.0"
authors = ["shaba721"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde_json = "1.0.39"
serde_derive = "1.0.92"
serde = "1.0.92"
regex = "1.1.7"